# Generated by Django 4.0.4 on 2022-05-25 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.date(2022, 5, 25)),
        ),
        migrations.AddField(
            model_name='user',
            name='money_owed',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
